spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/minesweeper-db}
    username: ${SPRING_DATASOURCE_USERNAME:tester}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres