CREATE TABLE IF NOT EXISTS games(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    width integer NOT NULL,
    height integer NOT NULL,
    mines_count integer NOT NULL,
    completed BOOL NOT NULL,
    mines varchar (1000) NOT NULL,
    opened varchar (1000) NOT NULL);